lang: en-us
title: Arhip Storozhev
author: Arhip Storozhev
theme: mystyle.css

menu:
  - title: home
    url: /

sections:
  - id: blog
    title: "Blog Posts"
  - id: events
    title: "Events, competitions, hackathons, etc."

bottom_sections:
  - title: "Noteworthy Open Source Projects"
    items:
      - title: Luna SSG
        url: https://github.com/stornov/luna-ssg
        description: "Fast and simple static site generator with blog support (used for this site)"

footer:
  - title: Contacts
    links:
      - text: Arhip Storozhev
        url: null
      - text: arsestordev@gmail.com
        url: mailto:arsestordev@gmail.com
  - title: Socials
    links:
      - text: GitHub
        url: https://github.com/stornov
  - title: Powered by
    links:
      - text: Luna SSG
        url: https://github.com/stornov/luna-ssg