lang: en-us
title: Arhip Storozhev
author: Arhip Storozhev
theme: mystyle.css

menu:
  - title: home
    url: /

sections:
  - id: blog
    title: "Blog Posts"
  - id: events
    title: "Events, competitions, hackathons, etc."

projects:
  - title: Luna SSG
    url: https://github.com/stornov/luna-ssg
    description: "My custom static site generator written in Python"
  - title: UNIT.HACK 2025 Entry
    url: https://github.com/stornov/unit.hack-2025
    description: "Hackathon project solving a case from NAUMEN."

footer:
  - title: Contacts
    links:
      - text: Arhip Storozhev
        url: null
      - text: arsestordev@gmail.com
        url: mailto:arsestordev@gmail.com
  - title: Socials
    links:
      - text: GitHub
        url: https://github.com/stornov
  - title: Powered by
    links:
      - text: Luna SSG
        url: https://github.com/stornov/luna-ssg