lang: en-us
title: Arhip Storozhev
author: Arhip Storozhev
theme: mystyle.css

menu:
  - title: home
    url: /

sections:
  - id: blog
    title: "Blog Posts"


footer:
  - links:
    - text: Arhip Storozhev
      url: null
    - text: arsestordev@gmail.com        
      url: mailto:arsestordev@gmail.com
  - links:
    - text: GitHub
      url: https://github.com/stornov
  - links:
    - text: Powered by Luna SSG
      url: https://github.com/stornov/luna-ssg